### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by kenvac** [kenvac/email_status#12]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

# Modules to migrate

- [ ] account_invoice_cancel_button
- [ ] account_invoice_cancel_reason
- [ ] email_status
- [ ] picking_update_cost_price
- [ ] product_where_used
- [ ] stock_picking_show_price
- [ ] stock_scrap
- [ ] stock_scrap_partner
- [ ] stock_scrap_reason
- [ ] stock_valuation_xlsx
