### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by kenvac** [kenvac/email_status#6]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] account_invoice_cancel_button
- [ ] account_invoice_cancel_reason
- [ ] email_status
- [ ] picking_update_cost_price
- [ ] stock_picking_show_price
- [ ] stock_valuation_xlsx
